name: schoolmate
description: A simple assistant to help you
publish_to: 'none'
version: 1.5.0+9

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.3

  # Files
  cross_file: ^0.3.3+8
  file_picker: ^6.1.1
  http: ^1.1.2

  #Image
  image_fade: ^0.6.2
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.2

  #Stats
  statsfl: ^2.3.0

  #Viewers
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  media_kit_libs_android_video: ^1.3.6
  media_kit_libs_linux: ^1.1.3
  media_kit_native_event_loop: ^1.0.8
  syncfusion_flutter_pdfviewer: ^24.1.45

  #Administration
  awesome_notifications: ^0.9.2
  awesome_notifications_core: ^0.9.1
  encrypt: ^5.0.3
  excel: ^4.0.2
  dio: ^5.4.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  intl: ^0.19.0
  pretty_qr_code: ^3.2.1
  shared_preferences: ^2.2.0
  supabase_flutter: ^2.2.0
  url_launcher: ^6.2.3
  uuid: ^4.3.2
  window_manager: ^0.3.7

  #Widgets
  scrollable_positioned_list: ^0.3.8
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  widget_zoom: ^0.0.3
  syncfusion_flutter_pdf: ^24.1.45
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  easy_rich_text: ^2.1.0
  rich_text_controller: ^1.4.2
  # google_generative_ai: ^0.2.0
  marquee: ^2.2.3
  animated_list_plus: ^0.5.2
  either_dart: ^1.0.0
  infinite_carousel: ^1.1.1
  bottom_bar_with_sheet: ^2.4.0
  collection: ^1.18.0
  material_table_view: ^4.0.2
  signature_kit: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
  
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa_normal.ttf
    - family: Honk
      fonts:
        - asset: assets/fonts/Honk_normal.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans_normal.ttf
        - asset: assets/fonts/JosefinSans_italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat_normal.ttf
        - asset: assets/fonts/Montserrat_italic.ttf
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito_normal.ttf
        - asset: assets/fonts/Nunito_italic.ttf
          style: italic
    - family: SometypeMono
      fonts:
        - asset: assets/fonts/SometypeMono_normal.ttf
        - asset: assets/fonts/SometypeMono_italic.ttf
          style: italic
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk_normal.ttf

flutter_native_splash:
  color: "#fdcc48"
  color_dark: "#282828"

  image: assets/schoolmate_eagle.png

  branding: assets/loading_light.png
  branding_dark: assets/loading_dark.png

  android_12:
    color: "#ffffff"
    color_dark: "#282828"
    
    image: assets/schoolmate_eagle.png
    icon_background_color: "#ffffff"
  
  android_gravity: center
  web_image_mode: center

flutter_launcher_icons:
  image_path_android: "assets/schoolmate_eagle_splash_screen.png"
  image_path_ios: "assets/schoolmate_eagle_splash_screen.png"
  android: true
  ios: false
  image_path: "assets/schoolmate_eagle.png"
  min_sdk_android: 19

  web:
    generate: true
    image_path: "assets/schoolmate_eagle_splash_screen.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  
  windows:
    generate: true
    image_path: "assets/schoolmate_eagle_splash_screen.png"
    icon_size: 256

  linux:
    generate: true
    image_path: "assets/schoolmate_eagle_splash_screen.png"
  
  macos:
    generate: true
    image_path: "assets/schoolmate_eagle_splash_screen.png"
  

  